services:
  mitsuba:
    build: .
    container_name: mitsuba-doppler2
    platform: linux/amd64
    volumes:
      - ./scenes:/MitsubaDopplerToF/scenes
      - ./results:/MitsubaDopplerToF/results
      - ./build/release:/MitsubaDopplerToF/build/release
    command: sleep infinity
